### ISSUE TITLE
mainColumn Not Visible with Multi Monitors

### ISSUE THREAD

**Issue by StevenPolley** [sgerbino/stellar#4]
I use a laptop and it works fine if I have no external displays connected.  If I connect an external display with a different resolution than my laptops display, the name and password text boxes, including the rectangle background are not present.  

I will attach a screenshot tomorrow when I am at work.  

I have tried with other SDDM themes and it works fine, and I will play around with the Mail.qml file until I find the cause.

**Comment by sgerbino** [comment]
Try changing `visible: primaryScreen` on line 66 of Main.qml
I think I deliberately did this so that I didn't see the login on both screens with my dual monitor setup.
